# Generated by Django 4.2.6 on 2023-10-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('famille', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Prof',
        ),
    ]
